import sqlobject as db

db.sqlhub.processConnection = db.connectionForURI("mysql://brewnome:br3wl0v3r@localhost/brewnome")

class Beer(db.SQLObject):
    beer_name = db.StringCol(length=100)
    beer_description = db.StringCol(length=255)
    beer_img_url = db.StringCol(length=255)
    beer_likes = db.IntCol(default=0)
    beer_dislikes = db.IntCol(default=0)
    beer_class = db.StringCol(length=64)
    beer_sub_class = db.StringCol(length=64)
    brewer_name = db.StringCol(length=64)
    brewer_country = db.StringCol(length=64)
    brewer_region = db.StringCol(length=64)
    beer_color = db.StringCol(length=64)
    carbonation = db.StringCol(length=64)
    heaviness_or_fullness = db.StringCol(length=64)
    hoppiness = db.IntCol()
    food_flavor_1 = db.StringCol(length=64)
    food_flavor_2 = db.StringCol(length=64)
    food_flavor_3 = db.StringCol(length=64)
    food_flavor_4 = db.StringCol(length=64)
    food_flavor_5 = db.StringCol(length=64)
    sweetness = db.StringCol(length=64)
    starch_grain_type_1 = db.StringCol(length=64)
    starch_grain_type_2 = db.StringCol(length=64)
    starch_grain_type_3 = db.StringCol(length=64)
    starch_grain_type_4 = db.StringCol(length=64)
    starch_grain_type_5 = db.StringCol(length=64)
    starch_grain_sub_type_1 = db.StringCol(length=64)
    starch_grain_sub_type_2 = db.StringCol(length=64)
    starch_grain_sub_type_3 = db.StringCol(length=64)
    starch_grain_sub_type_4 = db.StringCol(length=64)
    starch_grain_sub_type_5 = db.StringCol(length=64)
    malted_or_unmalted_starch_grain = db.StringCol(length=64)
    hops_type_1 = db.StringCol(length=64)
    hops_type_2 = db.StringCol(length=64)
    hops_type_3 = db.StringCol(length=64)
    hops_type_4 = db.StringCol(length=64)
    hops_type_5 = db.StringCol(length=64)
    yeast_type_1 = db.StringCol(length=64)
    yeast_type_2 = db.StringCol(length=64)
    yeast_type_3 = db.StringCol(length=64)
    yeast_type_4 = db.StringCol(length=64)
    yeast_type_5 = db.StringCol(length=64)
    seasonality	= db.StringCol(length=64)
    alcohol_percentage = db.DecimalCol(size=10, precision=2)
    brewer_volume_of_distribution = db.StringCol(length=64)
    bottle_retail_price = db.StringCol(length=64)
    roasting_time = db.StringCol(length=64)
    roasting_temperature = db.StringCol(length=64)
    clarifying_agents = db.StringCol(length=64)
    fermentation_style = db.StringCol(length=64)
    fermentation_temperature = db.StringCol(length=64)
    second_fermentation = db.StringCol(length=64)
    continuous_fermentation = db.StringCol(length=64)
    serving_temperature	= db.StringCol(length=64)
    crispness = db.StringCol(length=64)
    aroma = db.StringCol(length=64)
    head_retention = db.StringCol(length=64)
    cask_conditioning = db.StringCol(length=64)
    calorie_count = db.StringCol(length=64)
    spices_1 = db.StringCol(length=64)
    spices_2 = db.StringCol(length=64)
    spices_3 = db.StringCol(length=64)
    spices_4 = db.StringCol(length=64)
    spices_5 = db.StringCol(length=64)
    herbs_1 = db.StringCol(length=64)
    herbs_2 = db.StringCol(length=64)
    herbs_3 = db.StringCol(length=64)
    herbs_4 = db.StringCol(length=64)	
    herbs_5 = db.StringCol(length=64)
    clarity = db.StringCol(length=64)
    age = db.StringCol(length=64)
    og = db.DecimalCol(size=10, precision=2)

class Location(db.SQLObject):
    location_name= db.StringCol(length=64)
    lat = db.FloatCol()
    lng = db.FloatCol()

class Menu(db.SQLObject):
    menu_location = db.ForeignKey("Location", cascade=False)
    menu_beer = db.ForeignKey("Beer", cascade=False)

class User(db.SQLObject):
    user_fb_id = db.IntCol()

class Rating(db.SQLObject):
    rating_beer = db.ForeignKey("Beer", cascade=False)
    rating_user = db.ForeignKey("User", cascade=False)
    rating_rate = db.IntCol()

#class TaskQueue(db.SQLObject):
#    task_group = db.ForeignKey("TaskQueueGroup", cascade=False)
#    task_url = db.StringCol(length=255)
#    task_data = db.StringCol()
#    task_time = db.TimestampCol()

#class Summary(db.SQLObject):
#    summary_category = db.StringCol(length=64)
#    summary_type = db.StringCol(length=64)
#    summary_value = db.StringCol(length=64)
#    summary_result = db.StringCol(length=64)

#class VehicleMake(db.SQLObject):
#    make_code = db.StringCol(length=5)
#    make_description = db.StringCol(length=128)
#    total_make = db.IntCol()
#    total_make_fine_amt = db.CurrencyCol()
